---
# Common computer setup
- name: Remove the SNUC user
  user:
    name: snuc
    state: absent
    remove: yes
    force: yes

- name: Make sure Botnuvo user has permissions
  user:
    name: botnuvo
    groups: sudo,audio,dialout,plugdev

- name: Install some core tools
  apt:
    pkg: git,openssh-server,net-tools
