---
# Setup networking stuff
- name: Setup interface to communicate with mainboard
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces

- name: Setup udev rule for hokuyo laser
  copy:
    src: hokuyo
    dest: /etc/udev/rules.d/51-hokuyo.rules
